### ISSUE TITLE
Adjustments: contribution_amount and contributon_text are not exclusive

### ISSUE THREAD

**Issue by olliemath** [SuadeLabs/fire#147]
In particular, this is valid under a compliant JSON-schema validator, so long as `currency_code` is not present:
```json
{"id": "a", "contribution_amount": 123, "contribution_text": "hi", ....}
```

This is because the `oneOf` logic here https://github.com/SuadeLabs/fire/blob/master/v1-dev/adjustment.json#L62 is an exclusive or implemented like
```python
(a or b) and not (a and b)
```

# Solution

We should change this to
```json
"oneOf": [
   {"required": ["id", "date", "report_type", "row", "col", "contribution_amount"]},
   {"required": ["id", "date", "report_type", "row", "col", "contribution_text"]}
 ],
 "dependencies": {
      "contribution_amount": ["currency_code"]
}
```
this would make these fields exclusive and would mean that if `contribution_amount` is populated, `currency_code` must be too.

**Comment by muratabur** [comment]
Ah this is a good point! Could we do even better and make sure bidirectionally? e.g. `currency_code` _is not provided_ if `contribution_text` is provided?

so something like:

```json
"dependencies": {
      "contribution_amount": "currency_code",
      "currency_code": "contribution_amount"
}
```
