### ISSUE TITLE
XBRL and FIRE

### ISSUE THREAD

**Issue by mrtoddalexander** [SuadeLabs/fire#15]
With the more popular and widely adopted data exchange format standards such as XBRL, can this format be translated into XBRL format to form a formal verification / gap analysis of compliance requirements against the reported data? 

Are there any architecture diagrams of how FIRE data exchange format for regulatory data can be implemented or commonly should fit in an information infrastructure?

**Comment by muratabur** [comment]
@mrtoddalexander indeed, you are welcome to convert a json format to XML, XBRL or any other equivalent format. 

Regarding implementation, most people implement the schemas as tables in a relational database, but implementation should really be independent of the transmission format for the data.
