### ISSUE TITLE
Migrate country codes to ISO_3166-2 standard

### ISSUE THREAD

**Issue by artug** [SuadeLabs/fire#183]
Some regulators might consider relevant to have the country information disclosed by regions, so it could be interesting to start handling that by using ISO_3166-2 standard
https://en.wikipedia.org/wiki/ISO_3166-2

**Comment by olliemath** [comment]
The biggest decision to make is whether to allow ISO-3166-2 in the country field, or have a separate "subdivision" field like:
```json
"country": "AE",
"subdivision": "AE-DU",
```

Note that subdivision => country, so having both fields would increase the risk of contradictions like
```json
"country": "AE",
"subdivision": "GB-ENG",
```

**Comment by muratabur** [comment]
Yeah I think just expanding the allowed enums list for `country_code` to include the subdivisions would be best - I have never seen anyone use this kind of granularity though - is it needed for a particular regulation @artug ?

It also seems like it was hard to agree on the right hierarchy under the country code:

`GB - GBN` => Great Britain
`GB - UKM` => United Kingdom
`GB - EAW` => England & Wales
`GB - WLS` => Wales
`GB - CYM` => also Wales
`GB - CRD` or `GB - CRF` => Cardiff
`GB - CMD` => Camden

China has 4 municipalities and Estonia has 64!

**Comment by olliemath** [comment]
> As of 3 March 2022 there are 5,048 codes defined in ISO 3166-2.

I'm not sure that's something we want directly in the fire standard though? Should we accept a slightly expanded 3166-1, but not *all* subdivisions (e.g. just 4: `ENG`, `NIR`, `SCT`, `WLS` would probably be more than sufficient for the UK)

**Comment by muratabur** [comment]
:scream: 

is there a definitive list somewhere in the regs?

**Comment by artug** [comment]
Mmm, I didn't find a definitive list, just find this reference in documentation:
![image](https://user-images.githubusercontent.com/8413852/197256519-a43bde50-7633-4d39-87bf-d42697f318df.png)
https://www.bankofengland.co.uk/-/media/boe/files/statistics/data-collection/statistical-forms-taxonomy/taxonomy-124-release-note.pdf
Located here:
https://www.bankofengland.co.uk/statistics/data-collection/beeds

**Comment by olliemath** [comment]
> perhaps where we assigned a code before the ISO standard was updated

AG has been ISO for Antigua since 1974, when it was created, so I doubt that ;D
