### ISSUE TITLE
Reporting LEI column should have "min:20" and "max:20" in all schemas (now only in loan).

### ISSUE THREAD

**Issue by BabOuDev** [SuadeLabs/fire#20]
The only schema that has the "minLength" and "maxLength" fields in the Reporting LEI column is the "Loan" schema. This should be in all schemas as the LEI is always 20 characters.

**Comment by yumikab** [comment]
Made a merge request to amend the lei fields in the account and entity schemas.

**Comment by BabOuDev** [comment]
thanks !
