### ISSUE TITLE
Enhance securitisation attributes

### ISSUE THREAD

**Issue by muratabur** [SuadeLabs/fire#323]
<!DOCTYPE html>

<html>

<body>

excess_spread_type | no excess spread
-- | --
  | fixed - trapped
  | fixed – use or lose
  | variable – trapped
  | variable - use or lose
  |  
amortisation_system | Sequential amortisation
  | Pro-rata amortisation
  | Pro-rata amortisation changing to sequential amortisation. Compliant with STS criteria for on-balance sheet securitisations (Article 26c (5) of Regulation (EU) 2017/2402).
  | Pro-rata amortisation changing to sequential amortisation. Compliant with STS criteria for non-ABCP transactions (Guidelines on STS criteria for non-ABCP transactions and Article 21 (5) of Regulation (EU) 2017/2402
  | Pro-rata amortisation changing to sequential amortisation. Not compliant
  | Other amortisation system
  |  
retention_type | Vertical slice (securitisation positions): “retention of no less than 5 % of the nominal value of each of the tranches sold or transferred to the investors”
  | V - Vertical slice (securitised exposures): retention of no less than 5 % of the credit risk of each of the securitised exposures, if the credit risk thus retained with respect to such securitised exposures always ranks pari passu with, or is subordinated to, the credit risk that has been securitised with respect to those same exposures;B - Revolving exposures: ”in the case of securitisations of revolving exposures, retention of the originator’s interest of no less than 5 % of the nominal value of the securitised exposures”;
  | C- On-balance sheet: “retention of randomly selected exposures, equivalent to no less than 5 % of the nominal amount of the securitised exposures, where such exposures would otherwise have been securitised in the securitisation, provided that the number of potentially securitised exposures is no less than 100 at origination”;
  | D- First loss: “retention of the first loss tranche and, if necessary, other tranches having the same or a more severe risk profile than those transferred or sold to investors and not maturing any earlier than those transferred or sold to investors, so that the retention equals in total no less than 5 % of the nominal value of the securitised exposures”;
  | E – Exempted. This code shall be reported for those securitisations affected by the application of Article 6(6) of Regulation (EU) 2017/2402;
retention_percentage |  
type | Abs_CC_rec
  | Abs_SME_retail
  | Abs_wholesale_loans
  | Abs_SME_corporate
  | ABS_corporate
  | Abs_lease
  | Abs_trade_rec
  | Abs_wholesale_other
clean_up_call |  
seniority | Senior
  | Mezzanine
  | First_loss

</body>

</html>

**Comment by seelan93** [comment]
hey @muratabur do you want me to help do this?
