### ISSUE TITLE
Fire validator should be more verbose about what schemas are satisfied

### ISSUE THREAD

**Issue by jesper** [SuadeLabs/fire#7]
Most of the fields are optional, and as such, the validator turns green quite often - even if the data isn't exactly correct. It would be wonderful if the validator communicated if the data pasted was valid for "loans", "customers", etc.

**Comment by gobbledygook88** [comment]
FIRE validator repository created here: https://github.com/SuadeLabs/fire-validator
Shall move feature requests and issues over there henceforth.
